[book]
title = "Ghost Hunter 中微子数据分析排位赛"
authors = ["He Yufeng"]
description = "2024 Ghost Hunter 中微子数据分析排位赛赛事信息平台"
src = "./src"
language = "zh-CN"
multilingual = false

[preprocessor.katex]
after = ["links"]
output = "htmlAndMathml"
pre-render = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/thudep/Ghost-Hunter-Homepage/tree/main"
edit-url-template = "https://github.com/thudep/Ghost-Hunter-Homepage/edit/main/{path}"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
